environment:
  PGUSER: "postgres"
  PGPASSWORD: "Password12!"
  MYSQL_PASSWORD: "Password12!"

# Install scripts runs after repo cloning
install:
  - ps: .\test\script\appveyor\install-redis.ps1
  - ps: .\test\script\appveyor\install-elasticsearch.ps1
  - ps: .\test\script\appveyor\install-cassandra.ps1
  - ps: Install-Product node 8 # Latest LTS
  - npm install

# Services are started after all install scripts have run
services:
  - mysql
  - mongodb
  - postgresql
  - mssql2017

# Post-install test scripts
test_script:
  - node --version
  - npm --version
  - npm test

# Don't actually build
build: off
