generic-pool:
  versions: ^2.0.0 || ^3.1.0
  commands: node test/instrumentation/modules/generic-pool.js
mimic-response:
  versions: ^1.0.0
  commands: node test/instrumentation/modules/mimic-response.js
got-old:
  name: got
  versions: '>=4.0.0 <9.0.0'
  node: '>=5'
  commands: node test/instrumentation/modules/http/github-423.js
got-new:
  name: got
  versions: '>=9.0.0'
  node: '>=8.3'
  commands: node test/instrumentation/modules/http/github-423.js
mysql:
  versions: ^2.0.0
  commands:
    - node test/instrumentation/modules/mysql/mysql.js
    - node test/instrumentation/modules/mysql/pool-release-1.js
mysql2:
  versions: ^1.0.0
  commands:
    - node test/instrumentation/modules/mysql2/mysql.js
    - node test/instrumentation/modules/mysql2/pool-release-1.js
redis:
  versions: ^2.0.0
  commands: node test/instrumentation/modules/redis.js
ioredis-old:
  name: ioredis
  versions: '>=2 <3.1.3 || >3.1.3 <4' # v3.1.3 is broken in older versions of Node because of https://github.com/luin/ioredis/commit/d5867f7c7f03a770a8c0ca5680fdcbfcaf8488e7
  commands: node test/instrumentation/modules/ioredis.js
ioredis-new:
  name: ioredis
  versions: '^4.0.0'
  node: '>=6'
  commands: node test/instrumentation/modules/ioredis.js
pg:
  versions: '>=4 <8'
  peerDependencies:
    - bluebird@^3.0.0
    - knex@^0.13.0
  commands:
    - node test/instrumentation/modules/pg/pg.js
    - node test/instrumentation/modules/pg/knex.js
mongodb-core:
  versions: '>=1.2.19 <4'
  commands: node test/instrumentation/modules/mongodb-core.js
bluebird:
  versions: '>=2 <4'
  commands:
    - node test/instrumentation/modules/bluebird/bluebird.js
    - node test/instrumentation/modules/bluebird/cancel.js
knex:
  versions: ^0.15.0 || ^0.14.0 || ^0.13.0 || ^0.12.5 || <0.12.4 >0.11.6 || <0.11.6 >0.9.0
  commands: node test/instrumentation/modules/pg/knex.js
ws:
  versions: '>=1 <7'
  commands: node test/instrumentation/modules/ws.js
graphql:
  preinstall: rm -fr node_modules/express-graphql
  versions: '>=0.7.0 <0.11.0 || >=0.11.1 <15.0.0 || ^14.0.0-rc'
  commands: node test/instrumentation/modules/graphql.js
express:
  versions: '>=4'
  commands: node test/instrumentation/modules/express.js

express-graphql-1:
  name: express-graphql
  peerDependencies: graphql@^0.8.2
  versions: '0.6.1'
  commands: node test/instrumentation/modules/express-graphql.js

express-graphql-2:
  name: express-graphql
  peerDependencies: graphql@^0.9.0
  versions: '>=0.6.2 <0.6.6'
  commands: node test/instrumentation/modules/express-graphql.js

express-graphql-3:
  name: express-graphql
  peerDependencies: graphql@^0.10.0
  versions: '>=0.6.6 <0.6.8'
  commands: node test/instrumentation/modules/express-graphql.js

express-graphql-0.6.11_10:
  name: express-graphql
  peerDependencies: graphql@^0.10.0
  versions: '0.6.11'
  commands: node test/instrumentation/modules/express-graphql.js
express-graphql-0.6.11_11:
  name: express-graphql
  peerDependencies: graphql@^0.11.0
  versions: '0.6.11'
  commands: node test/instrumentation/modules/express-graphql.js

express-graphql-0.6.12_10:
  name: express-graphql
  peerDependencies: graphql@^0.10.0
  versions: '^0.6.12'
  commands: node test/instrumentation/modules/express-graphql.js
express-graphql-0.6.12_11:
  name: express-graphql
  peerDependencies: graphql@^0.11.0
  versions: '^0.6.12'
  commands: node test/instrumentation/modules/express-graphql.js
express-graphql-0.6.12_12:
  name: express-graphql
  peerDependencies: graphql@^0.12.0
  versions: '^0.6.12'
  commands: node test/instrumentation/modules/express-graphql.js
express-graphql-0.6.12_13:
  name: express-graphql
  peerDependencies: graphql@^0.13.0
  versions: '^0.6.12'
  commands: node test/instrumentation/modules/express-graphql.js

express-graphql-0.7,1_12:
  name: express-graphql
  peerDependencies: graphql@^0.12.0
  versions: '^0.7.1'
  commands: node test/instrumentation/modules/express-graphql.js
express-graphql-0.7.1_13:
  name: express-graphql
  peerDependencies: graphql@^0.13.0
  versions: '^0.7.1'
  commands: node test/instrumentation/modules/express-graphql.js
express-graphql-0.7.1_14:
  name: express-graphql
  peerDependencies: graphql@^14.0.0
  versions: '^0.7.1'
  commands: node test/instrumentation/modules/express-graphql.js

apollo-server-express-2_12:
  name: apollo-server-express
  preinstall: rm -fr node_modules/express-graphql
  peerDependencies: graphql@^0.12.0
  versions: '>=2.0.2'
  node: '>=6'
  commands: node test/instrumentation/modules/apollo-server-express.js
apollo-server-express-2_13:
  name: apollo-server-express
  preinstall: rm -fr node_modules/express-graphql
  peerDependencies: graphql@^0.13.0
  versions: '>=2.0.2'
  node: '>=6'
  commands: node test/instrumentation/modules/apollo-server-express.js
apollo-server-express-2_14:
  name: apollo-server-express
  preinstall: rm -fr node_modules/express-graphql
  peerDependencies: graphql@^14.0.0
  versions: '>=2.0.2'
  node: '>=6'
  commands: node test/instrumentation/modules/apollo-server-express.js

express-queue:
  versions: '>=0.0.11'
  commands: node test/instrumentation/modules/express-queue.js

koa-router:
  node: '>=6.0.0'
  peerDependencies: koa@2
  versions: '>=5.2.0 <8'
  commands: node test/instrumentation/modules/koa-router/index.js
elasticsearch:
  versions: '>=8.0.0'
  commands: node test/instrumentation/modules/elasticsearch.js
handlebars:
  versions: '*'
  commands: node test/instrumentation/modules/handlebars.js
hapi-no-async-await:
  name: hapi
  versions: '>=9.0.1 <17.0.0'
  commands: node test/instrumentation/modules/hapi.js
hapi-async-await:
  name: hapi
  node: '>=8.2'
  versions: '^17.0.0'
  commands: node test/instrumentation/modules/hapi.js

tedious:
  name: tedious
  versions: '>=0.0.5'
  commands: node test/instrumentation/modules/tedious.js

cassandra-driver:
  # 3.1.0 is broken
  versions: '>=3 <3.1.0 || >3.1.0 <4'
  commands:
    - node test/instrumentation/modules/cassandra/cassandra.js

restify:
  # All versions before 4.4 are unsupported. Additionally,
  # there are several broken releases that need to be skipped:
  # - 6.2.0
  # - 6.0.1
  # - 6.0.0
  # - 5.0.0
  versions: '>=4.4 <5 || >5 <6 || >6.0.1 <6.2 || >6.2'
  commands:
    - node test/instrumentation/modules/restify.js

finalhandler:
  versions: '*'
  commands:
    - node test/instrumentation/modules/finalhandler.js
