mysql:
  versions: ^2.0.0
  commands:
    - node test/instrumentation/modules/mysql/mysql.js
    - node test/instrumentation/modules/mysql/pool-release-1.js
redis:
  versions: ^2.0.0
  commands: node test/instrumentation/modules/redis.js
ioredis:
  versions: ^2.0.0
  commands: node test/instrumentation/modules/ioredis.js
pg:
  versions: >=4 <7
  commands: node test/instrumentation/modules/pg/pg.js
bluebird:
  versions: >=2 <4
  commands:
    - node test/instrumentation/modules/bluebird/bluebird.js
    - node test/instrumentation/modules/bluebird/cancel.js
