generic-pool:
  versions: ^2.0.0 || ^3.1.0
  commands: node test/instrumentation/modules/generic-pool.js
mimic-response:
  versions: ^1.0.0
  commands: node test/instrumentation/modules/mimic-response.js
got:
  versions: '>=4.0.0 <10.5.1 || >10.5.1' # v10.5.1 is broken
  commands: node test/instrumentation/modules/http/github-423.js
mysql:
  versions: ^2.0.0
  commands:
    - node test/instrumentation/modules/mysql/mysql.js
    - node test/instrumentation/modules/mysql/pool-release-1.js
mysql2:
  versions: '>=1.0.0 <1.6.2 || >1.6.2 <3' # v1.6.2 is broken: https://github.com/sidorares/node-mysql2/issues/869
  commands:
    - node test/instrumentation/modules/mysql2/mysql.js
    - node test/instrumentation/modules/mysql2/pool-release-1.js
redis:
  versions: ^2.0.0
  commands: node test/instrumentation/modules/redis.js
ioredis:
  versions: '>=2 <5'
  commands: node test/instrumentation/modules/ioredis.js
pg:
  versions: '>=4 <8'
  peerDependencies:
    - bluebird@^3.0.0
    - knex@^0.17.3
  commands:
    - node test/instrumentation/modules/pg/pg.js
    - node test/instrumentation/modules/pg/knex.js
mongodb-core:
  versions: '>=1.2.19 <4'
  commands: node test/instrumentation/modules/mongodb-core.js
mongodb:
  versions: '>=3.3'
  commands: node test/instrumentation/modules/mongodb.js
bluebird:
  versions: '>=2 <4'
  commands:
    - node test/instrumentation/modules/bluebird/bluebird.js
    - node test/instrumentation/modules/bluebird/cancel.js
knex:
  versions: '>=0.12.5 <0.21 || <0.12.4 >0.11.6 || <0.11.6 >0.9.0'
  commands: node test/instrumentation/modules/pg/knex.js
ws:
  versions: '>=1 <8'
  commands: node test/instrumentation/modules/ws.js
graphql:
  preinstall: npm uninstall express-graphql
  versions: '>=0.7.0 <0.11.0 || >=0.11.1 <15.0.0'
  commands: node test/instrumentation/modules/graphql.js
express:
  versions: '>=4'
  commands:
    - node test/instrumentation/modules/express/basic.js
    - node test/instrumentation/modules/express/capture-exceptions-off.js
    - node test/instrumentation/modules/express/capture-exceptions-on.js
    - node test/instrumentation/modules/express/set-framework.js

express-graphql-1:
  name: express-graphql
  preinstall: npm uninstall apollo-server-express
  peerDependencies: graphql@^0.8.2
  versions: '0.6.1'
  commands: node test/instrumentation/modules/express-graphql.js

express-graphql-2:
  name: express-graphql
  preinstall: npm uninstall apollo-server-express
  peerDependencies: graphql@^0.9.0
  versions: '>=0.6.2 <0.6.6'
  commands: node test/instrumentation/modules/express-graphql.js

express-graphql-3:
  name: express-graphql
  preinstall: npm uninstall apollo-server-express
  peerDependencies: graphql@^0.10.0
  versions: '>=0.6.6 <0.6.8'
  commands: node test/instrumentation/modules/express-graphql.js

express-graphql-0.6.11_10:
  name: express-graphql
  preinstall: npm uninstall apollo-server-express
  peerDependencies: graphql@^0.10.0
  versions: '0.6.11'
  commands: node test/instrumentation/modules/express-graphql.js
express-graphql-0.6.11_11:
  name: express-graphql
  preinstall: npm uninstall apollo-server-express
  peerDependencies: graphql@^0.11.0
  versions: '0.6.11'
  commands: node test/instrumentation/modules/express-graphql.js

express-graphql-0.6.12_10:
  name: express-graphql
  preinstall: npm uninstall apollo-server-express
  peerDependencies: graphql@^0.10.0
  versions: '^0.6.12'
  commands: node test/instrumentation/modules/express-graphql.js
express-graphql-0.6.12_11:
  name: express-graphql
  preinstall: npm uninstall apollo-server-express
  peerDependencies: graphql@^0.11.0
  versions: '^0.6.12'
  commands: node test/instrumentation/modules/express-graphql.js
express-graphql-0.6.12_12:
  name: express-graphql
  preinstall: npm uninstall apollo-server-express
  peerDependencies: graphql@^0.12.0
  versions: '^0.6.12'
  commands: node test/instrumentation/modules/express-graphql.js
express-graphql-0.6.12_13:
  name: express-graphql
  preinstall: npm uninstall apollo-server-express
  peerDependencies: graphql@^0.13.0
  versions: '^0.6.12'
  commands: node test/instrumentation/modules/express-graphql.js

express-graphql-0.7.1_12:
  name: express-graphql
  preinstall: npm uninstall apollo-server-express
  peerDependencies: graphql@^0.12.0
  versions: '>=0.7.1 <0.9.0'
  commands: node test/instrumentation/modules/express-graphql.js
express-graphql-0.7.1_13:
  name: express-graphql
  preinstall: npm uninstall apollo-server-express
  peerDependencies: graphql@^0.13.0
  versions: '>=0.7.1 <0.9.0'
  commands: node test/instrumentation/modules/express-graphql.js
express-graphql-0.7.1_14:
  name: express-graphql
  preinstall: npm uninstall apollo-server-express
  peerDependencies: graphql@^14.0.0
  versions: '>=0.7.1 <0.9.0'
  commands: node test/instrumentation/modules/express-graphql.js

express-graphql-0.9.0:
  name: express-graphql
  preinstall: npm uninstall apollo-server-express
  peerDependencies: graphql@^14.4.1
  versions: '>=0.9.0 <0.10.0'
  commands: node test/instrumentation/modules/express-graphql.js

apollo-server-express-2_12:
  name: apollo-server-express
  preinstall: npm uninstall express-graphql
  peerDependencies: graphql@^0.12.0
  versions: '>=2.0.4 <2.2 || >= 2.3.2'
  commands: node test/instrumentation/modules/apollo-server-express.js
apollo-server-express-2_13:
  name: apollo-server-express
  preinstall: npm uninstall express-graphql
  peerDependencies: graphql@^0.13.0
  versions: '>=2.0.4 <2.2 || >= 2.3.2'
  commands: node test/instrumentation/modules/apollo-server-express.js
apollo-server-express-2_14:
  name: apollo-server-express
  preinstall: npm uninstall express-graphql
  peerDependencies: graphql@^14.0.0
  versions: '>=2.0.4 <2.2 || >= 2.3.2'
  commands: node test/instrumentation/modules/apollo-server-express.js

express-queue:
  versions: '>=0.0.11'
  commands: node test/instrumentation/modules/express-queue.js

koa-router:
  peerDependencies: koa@2
  versions: '>=5.2.0 <9'
  commands: node test/instrumentation/modules/koa-router/old-name.js
'@koa/router':
  peerDependencies: koa@2
  versions: '>=8 <9'
  commands: node test/instrumentation/modules/koa-router/new-name.js

elasticsearch:
  versions: '>=8.0.0'
  commands: node test/instrumentation/modules/elasticsearch.js
handlebars:
  versions: '*'
  commands: node test/instrumentation/modules/handlebars.js
jade:
  versions: '>0.5.5'
  commands: node test/instrumentation/modules/jade.js
pug:
  versions: '0.1.0 || >2.0.0'
  commands: node test/instrumentation/modules/pug.js
hapi:
  versions: '>=9.0.1'
  commands:
    - node test/instrumentation/modules/hapi/basic-legacy-path.js
    - node test/instrumentation/modules/hapi/set-framework.js

'@hapi/hapi-old':
  name: '@hapi/hapi'
  versions: '>=17.0.0 <19.0.0'
  commands:
    - node test/instrumentation/modules/hapi/basic.js
    - node test/instrumentation/modules/hapi/set-framework-2.js
'@hapi/hapi-new':
  name: '@hapi/hapi'
  node: '>=12'
  versions: '>=19.0.0'
  commands:
    - node test/instrumentation/modules/hapi/basic.js
    - node test/instrumentation/modules/hapi/set-framework-2.js

tedious:
  name: tedious
  versions: '>=1.9 <2.7 || 3.x || >4.0.0'
  commands: node test/instrumentation/modules/tedious.js

cassandra-driver:
  versions: '>=3 <3.1.0 || >3.1.0 <5' # 3.1.0 is broken
  commands: node test/instrumentation/modules/cassandra-driver/index.js

restify:
  versions: '>=5.2.0'
  commands:
    - node test/instrumentation/modules/restify/basic.js
    - node test/instrumentation/modules/restify/set-framework.js

fastify:
  versions: '>=0.27.0 <0.29.0 || >0.29.0 <2.4.0 || >2.4.0'
  commands:
    - node test/instrumentation/modules/fastify/fastify.js
    - node test/instrumentation/modules/fastify/async-await.js
    - node test/instrumentation/modules/fastify/set-framework.js

finalhandler:
  versions: '*'
  commands: node test/instrumentation/modules/finalhandler.js

memcached:
  versions: '>=2.2.0'
  commands: node test/instrumentation/modules/memcached.js
