
# @elastic/elasticsearch
# - Version 7.7.0 included a change that broke usage with Node.js < 10.
#   Fixed in 7.7.1: https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/changelog-client.html#_7_7_1
#   Note: When this repo drops Node.js v8 support, `versions` can be simplified.
# - Version 7.12.0 dropped support for node v8.
# - Version 8's min node is v12. We only support the latest canary release (at
#   time of writing). The published '8.0.0-alpha.2' is *not* supported.
'@elastic/elasticsearch-v7.0-v7.12':
  name: '@elastic/elasticsearch'
  versions: '>=7.0.0 <7.7.0 || >7.7.0 <7.12.0'
  commands: node test/instrumentation/modules/@elastic/elasticsearch.test.js
'@elastic/elasticsearch-v7.12-v8':
  name: '@elastic/elasticsearch'
  versions: '>=7.12.0 <8.0.0'
  node: '>=10.0.0'
  commands: node test/instrumentation/modules/@elastic/elasticsearch.test.js
'@elastic/elasticsearch-canary':
  name: '@elastic/elasticsearch-canary'
  versions: '^8.0.0-canary.35'
  node: '>=12'
  commands: node test/instrumentation/modules/@elastic/elasticsearch-canary.test.js


tedious:
  name: tedious
  # - tedious@4.0.0 was broken, fixed in 4.0.1 by
  #   https://github.com/tediousjs/tedious/commit/4eceb48
  versions: '^1.9.0 || 2.x || 3.x || ^4.0.1 || 5.x || 6.x || 7.x || 8.x || 9.x'
  commands: node test/instrumentation/modules/tedious.test.js

cassandra-driver:
  # 3.1.0 is broken
  versions: '>=3 <3.1.0 || >3.1.0 <5'
  commands: node test/instrumentation/modules/cassandra-driver/index.test.js



finalhandler:
  versions: '*'
  commands: node test/instrumentation/modules/finalhandler.test.js

memcached:
  versions: '>=2.2.0'
  commands: node test/instrumentation/modules/memcached.test.js

body-parser:
  versions: '>=1.19.0'
  commands:
    - node test/sanitize-field-names/express.test.js

aws-sdk:
  # We want this version range:
  #   versions: '>=2.858 <3'
  # However, awk-sdk releases *very* frequently (almost every day) and there
  # is no need to test *all* those releases. Instead we statically list a subset
  # of versions to test.
  #
  # Maintenance note: This should be updated periodically using:
  #   ./dev-utils/aws-sdk-tav-versions.sh
  #
  # Test v2.858.0, every N=31 of 159 releases, and current latest.
  versions: '2.858.0 || 2.889.0 || 2.920.0 || 2.951.0 || 2.982.0 || 2.1013.0 || 2.1016.0 || >2.1016.0 <3'
  commands:
    - node test/instrumentation/modules/aws-sdk/s3.test.js
    - node test/instrumentation/modules/aws-sdk/sqs.test.js
    - node test/instrumentation/modules/aws-sdk/dynamodb.test.js
