ifdef::env-github[]
NOTE: Release notes are best read in our documentation at
https://www.elastic.co/guide/en/apm/agent/nodejs/current/release-notes.html[elastic.co]
endif::[]

////
Notes:
1. When adding a changelog entry, if the "Unreleased" section doesn't yet exist,
   please add the following under the "=== Node.js Agent version 3.x" header:

        ==== Unreleased

        [float]
        ===== Breaking changes

        [float]
        ===== Features

        [float]
        ===== Bug fixes

        [float]
        ===== Chores

2. When making a release, change the "==== Unreleased" section header to:

        [[release-notes-x.x.x]]
        ==== x.x.x - YYYY/MM/DD
////


[[release-notes-4.x]]
=== Node.js Agent version 1.x

==== Unreleased

[float]
===== Breaking changes

* Set the new minimum supported Node.js to version 14.
  Users of earlier Node.js versions can use elastic-apm-node v3.x, which
  supports back to Node.js v8.6.

[float]
===== Features

[float]
===== Bug fixes

[float]
===== Chores


[[release-notes-3.x]]
=== Node.js Agent version 3.x

XXX This CHANGELOG4 file will be merged into CHANGELOG.asciidoc before merging to main.

