[[release-notes-4.x]]
=== Node.js Agent version 1.x

==== Unreleased

[float]
===== Breaking changes

* Set the new minimum supported Node.js to version 14.5.0.
  Users of earlier Node.js versions can use elastic-apm-node v3.x, which
  supports back to Node.js v8.6.

* Ignore a `timer` option passed to `startTransaction()` and `startSpan()` APIs.
  This option was never documented. It would be surprising if any user is
  impacted by this.

* Remove long deprecated support for the `ELASTIC_APM_`-prefixed environment
  variables for the <<kubernetes-node-name,Kubernetes config options>>. For
  example, one must use `KUBERNETES_POD_NAME` and not
  `ELASTIC_APM_KUBERNETES_POD_NAME`. ({issues}2661[#2661])

* The config option `filterHttpHeaders` is now *removed*. ({pull}3539[#3539])

[float]
===== Features

[float]
===== Bug fixes

[float]
===== Chores

* Add a warning message when a duration config option is provided
  without units. ({issues}2121[#2121])

[[release-notes-3.x]]
=== Node.js Agent version 3.x

XXX This CHANGELOG4 file will be merged into CHANGELOG.asciidoc before merging to main.

