#!/bin/bash
mv test/metrics/index.js mv test/metrics/index.test.js
mv test/agent.js test/agent.test.js
mv test/babel/src.js test/babel/src.test.js
mv test/benchmarks/001-transaction-and-span-no-stack-trace.js test/benchmarks/001-transaction-and-span-no-stack-trace.test.js
mv test/benchmarks/002-transaction-and-span-overhead-realistic-size.js test/benchmarks/002-transaction-and-span-overhead-realistic-size.test.js
mv test/benchmarks/003-transaction-and-span-with-stack-trace.js test/benchmarks/003-transaction-and-span-with-stack-trace.test.js
mv test/benchmarks/004-transaction.js test/benchmarks/004-transaction.test.js
mv test/benchmarks/005-transaction-reading-file.js test/benchmarks/005-transaction-reading-file.test.js
mv test/benchmarks/utils/analyzer.js test/benchmarks/utils/analyzer.test.js
mv test/benchmarks/utils/apm-server.js test/benchmarks/utils/apm-server.test.js
mv test/benchmarks/utils/bench.js test/benchmarks/utils/bench.test.js
mv test/benchmarks/utils/callstack.js test/benchmarks/utils/callstack.test.js
mv test/benchmarks/utils/result-logger.js test/benchmarks/utils/result-logger.test.js
mv test/central-config-disabled.js test/central-config-disabled.test.js
mv test/central-config-enabled.js test/central-config-enabled.test.js
mv test/cloud-metadata/callback-coordination.js test/cloud-metadata/callback-coordination.test.js
mv test/cloud-metadata/index.js test/cloud-metadata/index.test.js
mv test/cloud-metadata/test-server.js test/cloud-metadata/test-server.test.js
mv test/config.js test/config.test.js
mv test/filters.js test/filters.test.js
mv test/http-request.js test/http-request.test.js
mv test/instrumentation/async-await.js test/instrumentation/async-await.test.js
mv test/instrumentation/async-hooks.js test/instrumentation/async-hooks.test.js
mv test/instrumentation/context.js test/instrumentation/context.test.js
mv test/instrumentation/github-issue-75.js test/instrumentation/github-issue-75.test.js
mv test/instrumentation/index.js test/instrumentation/index.test.js
mv test/instrumentation/modules/@elastic/elasticsearch.js test/instrumentation/modules/@elastic/elasticsearch.test.js
mv test/instrumentation/modules/apollo-server-express.js test/instrumentation/modules/apollo-server-express.test.js
mv test/instrumentation/modules/aws-sdk/fixtures-sqs.js test/instrumentation/modules/aws-sdk/fixtures-sqs.test.js
mv test/instrumentation/modules/aws-sdk/fixtures/use-s3.js test/instrumentation/modules/aws-sdk/fixtures/use-s3.test.js
mv test/instrumentation/modules/aws-sdk/sqs.js test/instrumentation/modules/aws-sdk/sqs.test.js
mv test/instrumentation/modules/bluebird/bluebird.js test/instrumentation/modules/bluebird/bluebird.test.js
mv test/instrumentation/modules/bluebird/cancel.js test/instrumentation/modules/bluebird/cancel.test.js
mv test/instrumentation/modules/cassandra-driver/index.js test/instrumentation/modules/cassandra-driver/index.test.js
mv test/instrumentation/modules/elasticsearch.js test/instrumentation/modules/elasticsearch.test.js
mv test/instrumentation/modules/express-graphql.js test/instrumentation/modules/express-graphql.test.js
mv test/instrumentation/modules/express-queue.js test/instrumentation/modules/express-queue.test.js
mv test/instrumentation/modules/express/basic.js test/instrumentation/modules/express/basic.test.js
mv test/instrumentation/modules/express/capture-exceptions-off.js test/instrumentation/modules/express/capture-exceptions-off.test.js
mv test/instrumentation/modules/express/capture-exceptions-on.js test/instrumentation/modules/express/capture-exceptions-on.test.js
mv test/instrumentation/modules/express/set-framework.js test/instrumentation/modules/express/set-framework.test.js
mv test/instrumentation/modules/fastify/async-await.js test/instrumentation/modules/fastify/async-await.test.js
mv test/instrumentation/modules/fastify/fastify.js test/instrumentation/modules/fastify/fastify.test.js
mv test/instrumentation/modules/fastify/set-framework.js test/instrumentation/modules/fastify/set-framework.test.js
mv test/instrumentation/modules/finalhandler.js test/instrumentation/modules/finalhandler.test.js
mv test/instrumentation/modules/generic-pool.js test/instrumentation/modules/generic-pool.test.js
mv test/instrumentation/modules/graphql.js test/instrumentation/modules/graphql.test.js
mv test/instrumentation/modules/handlebars.js test/instrumentation/modules/handlebars.test.js
mv test/instrumentation/modules/hapi/basic-legacy-path.js test/instrumentation/modules/hapi/basic-legacy-path.test.js
mv test/instrumentation/modules/hapi/basic.js test/instrumentation/modules/hapi/basic.test.js
mv test/instrumentation/modules/hapi/set-framework-hapi.js test/instrumentation/modules/hapi/set-framework-hapi.test.js
mv test/instrumentation/modules/hapi/set-framework-hapihapi.js test/instrumentation/modules/hapi/set-framework-hapihapi.test.js
mv test/instrumentation/modules/hapi/shared.js test/instrumentation/modules/hapi/shared.test.js
mv test/instrumentation/modules/http/aborted-requests-disabled.js test/instrumentation/modules/http/aborted-requests-disabled.test.js
mv test/instrumentation/modules/http/aborted-requests-enabled.js test/instrumentation/modules/http/aborted-requests-enabled.test.js
mv test/instrumentation/modules/http/aws.js test/instrumentation/modules/http/aws.test.js
mv test/instrumentation/modules/http/basic.js test/instrumentation/modules/http/basic.test.js
mv test/instrumentation/modules/http/bind-write-head-to-transaction.js test/instrumentation/modules/http/bind-write-head-to-transaction.test.js
mv test/instrumentation/modules/http/blacklisting.js test/instrumentation/modules/http/blacklisting.test.js
mv test/instrumentation/modules/http/disabling.js test/instrumentation/modules/http/disabling.test.js
mv test/instrumentation/modules/http/github-179.js test/instrumentation/modules/http/github-179.test.js
mv test/instrumentation/modules/http/github-423.js test/instrumentation/modules/http/github-423.test.js
mv test/instrumentation/modules/http/outgoing.js test/instrumentation/modules/http/outgoing.test.js
mv test/instrumentation/modules/http/request-to-url.js test/instrumentation/modules/http/request-to-url.test.js
mv test/instrumentation/modules/http/request.js test/instrumentation/modules/http/request.test.js
mv test/instrumentation/modules/http/sse.js test/instrumentation/modules/http/sse.test.js
mv test/instrumentation/modules/http2.js test/instrumentation/modules/http2.test.js
mv test/instrumentation/modules/ioredis.js test/instrumentation/modules/ioredis.test.js
mv test/instrumentation/modules/jade.js test/instrumentation/modules/jade.test.js
mv test/instrumentation/modules/koa-router/new-name.js test/instrumentation/modules/koa-router/new-name.test.js
mv test/instrumentation/modules/koa-router/old-name.js test/instrumentation/modules/koa-router/old-name.test.js
mv test/instrumentation/modules/koa-router/shared.js test/instrumentation/modules/koa-router/shared.test.js
mv test/instrumentation/modules/koa/set-framework.js test/instrumentation/modules/koa/set-framework.test.js
mv test/instrumentation/modules/memcached.js test/instrumentation/modules/memcached.test.js
mv test/instrumentation/modules/mimic-response.js test/instrumentation/modules/mimic-response.test.js
mv test/instrumentation/modules/mongodb-core.js test/instrumentation/modules/mongodb-core.test.js
mv test/instrumentation/modules/mongodb.js test/instrumentation/modules/mongodb.test.js
mv test/instrumentation/modules/mysql/mysql.js test/instrumentation/modules/mysql/mysql.test.js
mv test/instrumentation/modules/mysql/pool-release-1.js test/instrumentation/modules/mysql/pool-release-1.test.js
mv test/instrumentation/modules/mysql2/mysql.js test/instrumentation/modules/mysql2/mysql.test.js
mv test/instrumentation/modules/mysql2/pool-release-1.js test/instrumentation/modules/mysql2/pool-release-1.test.js
mv test/instrumentation/modules/pg/knex.js test/instrumentation/modules/pg/knex.test.js
mv test/instrumentation/modules/pg/pg.js test/instrumentation/modules/pg/pg.test.js
mv test/instrumentation/modules/pug.js test/instrumentation/modules/pug.test.js
mv test/instrumentation/modules/redis.js test/instrumentation/modules/redis.test.js
mv test/instrumentation/modules/restify/basic.js test/instrumentation/modules/restify/basic.test.js
mv test/instrumentation/modules/restify/set-framework.js test/instrumentation/modules/restify/set-framework.test.js
mv test/instrumentation/modules/tedious.js test/instrumentation/modules/tedious.test.js
mv test/instrumentation/modules/ws.js test/instrumentation/modules/ws.test.js
mv test/instrumentation/native-promises.js test/instrumentation/native-promises.test.js
mv test/instrumentation/span.js test/instrumentation/span.test.js
mv test/instrumentation/timer.js test/instrumentation/timer.test.js
mv test/instrumentation/transaction.js test/instrumentation/transaction.test.js
mv test/integration/503.js test/integration/503.test.js
mv test/integration/abort-on-invalid-cert.js test/integration/abort-on-invalid-cert.test.js
mv test/integration/allow-invalid-cert.js test/integration/allow-invalid-cert.test.js
mv test/integration/api-schema/basic.js test/integration/api-schema/basic.test.js
mv test/integration/api-schema/capture-error-log-stack-traces.js test/integration/api-schema/capture-error-log-stack-traces.test.js
mv test/integration/api-schema/capture-span-stack-traces.js test/integration/api-schema/capture-span-stack-traces.test.js
mv test/integration/api-schema/source-lines-error-frames.js test/integration/api-schema/source-lines-error-frames.test.js
mv test/integration/api-schema/source-lines-span-frames.js test/integration/api-schema/source-lines-span-frames.test.js
mv test/integration/no-sampling.js test/integration/no-sampling.test.js
mv test/integration/server-url-path.js test/integration/server-url-path.test.js
mv test/integration/skip-internal-http-spans.js test/integration/skip-internal-http-spans.test.js
mv test/integration/socket-close.js test/integration/socket-close.test.js
mv test/integration/verify-server-ca-cert.js test/integration/verify-server-ca-cert.test.js
mv test/lambda/callbacks.js test/lambda/callbacks.test.js
mv test/lambda/context.js test/lambda/context.test.js
mv test/lambda/mock/agent.js test/lambda/mock/agent.test.js
mv test/lambda/mock/transaction.js test/lambda/mock/transaction.test.js
mv test/lambda/promises.js test/lambda/promises.test.js
mv test/logging.js test/logging.test.js
mv test/metrics/breakdown.js test/metrics/breakdown.test.js
mv test/outcome.js test/outcome.test.js
mv test/parsers.js test/parsers.test.js
mv test/redact-secrets/is-secret.js test/redact-secrets/is-secret.test.js
mv test/redact-secrets/redact-secrets.js test/redact-secrets/redact-secrets.test.js
mv test/sanitize-field-names/express.js test/sanitize-field-names/express.test.js
mv test/sanitize-field-names/fastify.js test/sanitize-field-names/fastify.test.js
mv test/sanitize-field-names/hapi.js test/sanitize-field-names/hapi.test.js
mv test/sanitize-field-names/koa.js test/sanitize-field-names/koa.test.js
mv test/sanitize-field-names/main.js test/sanitize-field-names/main.test.js
mv test/sanitize-field-names/restify.js test/sanitize-field-names/restify.test.js
mv test/script/cli.js test/script/cli.test.js
mv test/sourcemaps/fixtures/lib/error-broken.js test/sourcemaps/fixtures/lib/error-broken.test.js
mv test/sourcemaps/fixtures/lib/error-inline-broken.js test/sourcemaps/fixtures/lib/error-inline-broken.test.js
mv test/sourcemaps/fixtures/lib/error-inline.js test/sourcemaps/fixtures/lib/error-inline.test.js
mv test/sourcemaps/fixtures/lib/error-map-missing.js test/sourcemaps/fixtures/lib/error-map-missing.test.js
mv test/sourcemaps/fixtures/lib/error-src-embedded.js test/sourcemaps/fixtures/lib/error-src-embedded.test.js
mv test/sourcemaps/fixtures/lib/error-src-missing.js test/sourcemaps/fixtures/lib/error-src-missing.test.js
mv test/sourcemaps/fixtures/lib/error.js test/sourcemaps/fixtures/lib/error.test.js
mv test/sourcemaps/fixtures/src/error.js test/sourcemaps/fixtures/src/error.test.js
mv test/sourcemaps/index.js test/sourcemaps/index.test.js
mv test/span-frames-min-duration.js test/span-frames-min-duration.test.js
mv test/stacktraces/fixtures/capture-error-string.js test/stacktraces/fixtures/capture-error-string.test.js
mv test/stacktraces/fixtures/circular-stack.js test/stacktraces/fixtures/circular-stack.test.js
mv test/stacktraces/fixtures/dist/throw-an-error-with-sourcemap.js test/stacktraces/fixtures/dist/throw-an-error-with-sourcemap.test.js
mv test/stacktraces/fixtures/send-a-span.js test/stacktraces/fixtures/send-a-span.test.js
mv test/stacktraces/fixtures/throw-an-error.js test/stacktraces/fixtures/throw-an-error.test.js
mv test/start/env/test.js test/start/env/test.test.js
mv test/start/file/elastic-apm-node.js test/start/file/elastic-apm-node.test.js
mv test/start/file/test.js test/start/file/test.test.js
mv test/test.js test/test.test.js
mv test/tracecontext/sample_rate.js test/tracecontext/sample_rate.test.js
mv test/tracecontext/tracestate.js test/tracecontext/tracestate.test.js
mv test/types/commonjs.js test/types/commonjs.test.js
mv test/uncaught-exceptions/log-uncaught-exceptions-off.js test/uncaught-exceptions/log-uncaught-exceptions-off.test.js
mv test/uncaught-exceptions/log-uncaught-exceptions-on.js test/uncaught-exceptions/log-uncaught-exceptions-on.test.js
mv test/wildcard-matcher.js test/wildcard-matcher.test.js
