# Config file for `updatecli compose ...`.
# https://www.updatecli.io/docs/core/compose/
policies:
  - name: Handle apm-data server specs
    policy: ghcr.io/elastic/oblt-updatecli-policies/apm/apm-data-spec:0.6.0@sha256:c0bbdec23541bed38df1342c95aeb601530a113db1ff11715c1c7616ed5e9e8b
    values:
      - .ci/updatecli/values.d/scm.yml
      - .ci/updatecli/values.d/apm-data-spec.yml

  - name: Handle apm json specs
    policy: ghcr.io/elastic/oblt-updatecli-policies/apm/apm-json-specs:0.6.0@sha256:e5a74c159ceed02fd20515ea76fa25ff81e3ccf977e74e636f9973db86aa52a5
    values:
      - .ci/updatecli/values.d/scm.yml
      - .ci/updatecli/values.d/apm-json-specs.yml
