version: '2.1'

services:
  cassandra:
    build:
      context: cassandra
      dockerfile: Dockerfile
    ports:
      - "9042:9042"
      - "7000:7000"

  elasticsearch:
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "network.host="
      - "transport.host=127.0.0.1"
      - "http.host=0.0.0.0"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
      - "9230:9300"

  mongodb:
    build:
      context: mongodb
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--quiet"]
      interval: 1s
      timeout: 10s
      retries: 30

  mssql:
    build:
      context: mssql
      dockerfile: Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - sa_password=${SA_PASSWORD}
    ports:
      - "1433:1433"

  mysql:
    build:
      context: mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql" ,"-h", "127.0.0.1", "-P", "3306", "-u", "root", "-e", "SELECT 1"]
      interval: 1s
      timeout: 10s
      retries: 30

  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1s
      timeout: 10s
      retries: 30

  redis:
    build:
      context: redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 10s
      retries: 30
