# The node.js project produces "nightly" builds of the tip of *some*
# development branches. They get uploaded to:
# https://nodejs.org/download/nightly/
#
# My observation is that nightly builds are only made for the next major
# version *up to the point there is a release of that version*.  For example,
# at time of writing, there is not yet a v17 release of node, and
# "v17.0.0-nightly*" builds are being created. Once a v17.0.0 release has been
# made, these will stop and there will be no value in testing v17 nightlies.
#
NODEJS_VERSION:
  - "20"
