'use stirct'

var afterAll = require('after-all')
var stackman = require('stackman')({ filter: '/node_modules/opbeat/' })
var knownGroupingKeys = require('lru-cache')({ max: 5000 })
var debug = require('debug')('opbeat')
var parsers = require('../parsers')

exports.encode = encode
exports.transactionGroupingKey = transactionGroupingKey

/**
 * Encodes recorded transactions into a format expected by the Opbeat intake
 * API.
 *
 * samples:
 *   An array containing objects of type Transaction. It's expected that each
 *   Transaction have a unique name within a 15ms window based on its duration.
 *
 * durations:
 *   An object whos keys are generated by `transactionGroupingKey`. Each value
 *   is an array of floats representing the duration in milliseconds of each
 *   recorded Transaction that belongs to that key.
 *
 * cb:
 *   A callback which will be called with the encoded data.
 */
function encode (samples, durations, cb) {
  var transactions = groupTransactions(samples, durations)
  var traces = [].concat.apply([], samples.map(function (trans) {
    return trans.traces
  }))
  var groups = groupTraces(traces)
  var raw = rawTransactions(samples)

  addStackTracesToTraceGroups(groups, traces, function () {
    cb({
      transactions: transactions,
      traces: {
        groups: groups,
        raw: raw
      }
    })
  })
}

function groupTransactions (samples, durations) {
  var groups = groupByKey(samples, transactionGroupingKey)

  return Object.keys(groups).map(function (key) {
    var trans = groups[key][0] // a transaction to represent this group
    return {
      transaction: trans.name,
      result: trans.result,
      kind: trans.type,
      timestamp: new Date(groupingTs(trans._start)).toISOString(),
      durations: durations[key]
    }
  })
}

function groupTraces (traces) {
  var groups = groupByKey(traces, traceGroupingKey)

  return Object.keys(groups).map(function (key, index) {
    var trace = groups[key][0] // a trace to represent this group
    groups[key].forEach(function (trace) {
      trace._groupIndex = index
    })
    return {
      transaction: trace.transaction.name,
      signature: trace.signature,
      kind: trace.type,
      timestamp: new Date(groupingTs(trace._start)).toISOString(),
      parents: trace.ancestors(),
      extra: trace.extra
    }
  })
}

function rawTransactions (transactions) {
  var raw = []
  transactions.forEach(function (trans) {
    if (trans.traces.length === 0) return
    var arr = rawTraces(trans.traces)
    arr.unshift(trans.duration())
    if (trans.req) {
      var meta = {
        http: parsers.parseRequest(trans.req, {body: trans._agent._logBody}),
        extra: {
          node: process.version,
          uuid: trans._uuid
        }
      }

      // common Express/Hapi patterns to store user information
      var user = trans.req.user || (trans.req.auth && trans.req.auth.credentials)
      if (user) {
        meta.user = {}
        if (typeof user.authenticated === 'boolean') meta.user.is_authenticated = user.authenticated
        if (typeof user.id === 'string' || typeof user.id === 'number') meta.user.id = user.id
        else if (typeof user._id === 'string' || typeof user._id === 'number') meta.user.id = user._id
        if (typeof user.username === 'string') meta.user.username = user.username
        else if (typeof user.name === 'string') meta.user.username = user.name
        if (typeof user.email === 'string') meta.user.email = user.email
      }

      arr.push(meta)
    }
    raw.push(arr)
  })
  return raw
}

function rawTraces (traces) {
  return traces.map(function (trace) {
    return [trace._groupIndex, trace.startTime(), trace.duration()]
  })
}

function addStackTracesToTraceGroups (groups, traces, cb) {
  var processed = []
  var next = afterAll(cb)
  traces.forEach(function (trace) {
    var index = trace._groupIndex
    if (~processed.indexOf(index)) return
    processed.push(index)

    var key = stackTraceGroupingKey(trace)
    if (knownGroupingKeys.get(key)) return
    knownGroupingKeys.set(key, true)

    var done = next()
    traceFrames(trace, function (frames) {
      if (frames) groups[index].extra._frames = frames.reverse()
      done()
    })
  })
}

function traceFrames (trace, cb) {
  if (trace._stackObj.frames) {
    process.nextTick(function () {
      cb(trace._stackObj.frames)
    })
    return
  }

  stackman(trace._stackObj.err, function (stack) {
    if (!stack.frames) {
      debug('could not capture stack trace for trace %o', { uuid: trace.transaction.uuid, signature: trace.signature, type: trace.type })
      cb()
      return
    }
    var frames = stack.frames.map(parsers.parseCallsite)
    trace._stackObj.frames = frames
    cb(frames)
  })
}

/**
 * Group an array (arr) of objects using the given grouping function (grouper).
 *
 * Only requirement is that the grouping function - given an object - returns a
 * key that should be used to group that object.
 *
 * Returns an object where each key represents a group. Each value in the
 * object is an array containing the objects that fall into that group.
 */
function groupByKey (arr, grouper) {
  var groups = {}

  arr.forEach(function (obj) {
    var key = grouper(obj)
    if (key in groups) groups[key].push(obj)
    else groups[key] = [obj]
  })

  return groups
}

function transactionGroupingKey (trans) {
  return groupingTs(trans._start) +
    '|' + trans.name +
    '|' + trans.result +
    '|' + trans.type
}

function traceGroupingKey (trace) {
  return groupingTs(trace.transaction._start) +
    '|' + trace.transaction.name +
    '|' + trace.ancestors().join('|') +
    '|' + trace.signature
}

function stackTraceGroupingKey (trace) {
  return trace.type +
    '|' + trace.signature +
    '|' + trace.transaction.name +
    '|' + trace.ancestors().join('|')
}

/**
 * Convert a number representing the milliseconds elapsed since the UNIX epoch
 * to whole minutes.
 *
 * Or in other words it converts:
 *   2016-10-23T15:23:53.345Z
 * To:
 *   2016-10-23T15:23:00.000Z
 */
function groupingTs (ms) {
  return Math.floor(ms / 1000 / 60) * 1000 * 60
}
