/*
 * Copyright Elasticsearch B.V. and other contributors where applicable.
 * Licensed under the BSD 2-Clause License; you may not use this file except in
 * compliance with the BSD 2-Clause License.
 */

const INTAKE_STRING_MAX_SIZE = 1024
const CAPTURE_ERROR_LOG_STACK_TRACES_NEVER = 'never'
const CAPTURE_ERROR_LOG_STACK_TRACES_MESSAGES = 'messages'
const CAPTURE_ERROR_LOG_STACK_TRACES_ALWAYS = 'always'
const CONTEXT_MANAGER_PATCH = 'patch'
const CONTEXT_MANAGER_ASYNCHOOKS = 'asynchooks'
const CONTEXT_MANAGER_ASYNCLOCALSTORAGE = 'asynclocalstorage'
const TRACE_CONTINUATION_STRATEGY_CONTINUE = 'continue'
const TRACE_CONTINUATION_STRATEGY_RESTART = 'restart'
const TRACE_CONTINUATION_STRATEGY_RESTART_EXTERNAL = 'restart_external'

// Exports
module.exports = {
  INTAKE_STRING_MAX_SIZE,
  CAPTURE_ERROR_LOG_STACK_TRACES_NEVER,
  CAPTURE_ERROR_LOG_STACK_TRACES_MESSAGES,
  CAPTURE_ERROR_LOG_STACK_TRACES_ALWAYS,
  CONTEXT_MANAGER_PATCH,
  CONTEXT_MANAGER_ASYNCHOOKS,
  CONTEXT_MANAGER_ASYNCLOCALSTORAGE,
  TRACE_CONTINUATION_STRATEGY_CONTINUE,
  TRACE_CONTINUATION_STRATEGY_RESTART,
  TRACE_CONTINUATION_STRATEGY_RESTART_EXTERNAL
}
