version: '2.1'

services:
  kafka:
    extends:
      file: docker-compose.yml
      service: kafka
  node_tests:
    extends:
      file: docker-compose-node-test.yml
      service: node_tests
    depends_on:
      localstack:
        condition: service_healthy

volumes:
  nodelafkadata:
    driver: local
