# This Makefile can be used to rebuild dist/... from src/... if necessary.
# However, this is mostly here to be self-documenting. I don't expect this
# test code to need to change.
#
# Prerequisite: You have TypeScript installed. That can be done via something
# like 'npm install -g typescript'.

.PHONY: all
all:
	tsc
