:framework: custom Node.js

[[custom-stack]]

ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/nodejs/current/custom-stack.html[elastic.co]
endif::[]

=== Get started with a custom Node.js stack

include::./shared-set-up.asciidoc[tag=introduction]

If you are using Express, hapi, Koa, Restify, Fastify, or AWS Lambda,
we recommend that you read these articles instead:

include::set-up.asciidoc[tag=web-frameworks-list]

[float]
[[custom-stack-installation]]
==== Installation

Add the `elastic-apm-node` module as a dependency to your application:

[source,bash]
----
npm install elastic-apm-node --save
----

[float]
[[custom-stack-initialization]]
==== Initialization

It's important that the agent is started before you require *any* other modules in your Node.js application - i.e. before `http` and before your router etc.

This means that you should probably require and start the agent in your application's main file (usually `index.js`, `server.js` or `app.js`).

Here's a simple example of how Elastic APM is normally required and started:

[source,js]
----
// Add this to the VERY top of the first file loaded in your app
var apm = require('elastic-apm-node').start({
  // Override service name from package.json
  // Allowed characters: a-z, A-Z, 0-9, -, _, and space
  serviceName: '',

  // Use if APM Server requires a token
  secretToken: '',

  // Use if APM Server uses API keys for authentication
  apiKey: '',

  // Set custom APM Server URL (default: http://127.0.0.1:8200)
  serverUrl: '',
})
----

The agent will now monitor the performance of your application and record any uncaught exceptions.

[float]
[[custom-stack-advanced-configuration]]
===== Advanced configuration

include::./shared-set-up.asciidoc[tag=advanced-configuration]

[float]
[[custom-stack-full-documentation]]
===== Full documentation

* <<advanced-setup,Setup and Configuration>>
* <<api,API Reference>>

[float]
[[custom-stack-performance-monitoring]]
==== Performance monitoring

include::./shared-set-up.asciidoc[tag=performance-monitoring]

[float]
[[custom-stack-route-naming]]
===== Route naming

The Node.js agent tracks incoming HTTP requests to your application in what are called "transactions".
All transactions with the same name are grouped together automatically.

In a normal web application, you want to name transactions based on the route that matches the incoming HTTP request.
So say you have a route to display posts on a blog identified by `GET /posts/{id}`.
You want requests `GET /posts/12`, `GET /posts/42` etc to be grouped together under a transaction named `GET /posts/{id}`.

If you are using Express, hapi, koa-router, Restify, or Fastify this naming happens automatically based on the names of your routes.
If you use another framework or a custom router you will see that the transactions are simply grouped together in a few big chunks named "unknown route".
In that case,
you will need to help us out a little by supplying a name for each transaction.
You can do that by calling <<apm-set-transaction-name,`apm.setTransactionName()`>> at any time during the request with the name of the transaction as the first argument.

Excerpt of an application using the https://github.com/watson/patterns[patterns] module for route handling:

[source,js]
----
var apm = require('elastic-apm-node').start()
var http = require('http')
var patterns = require('patterns')()

// Setup routes and their respective route handlers
patterns.add('GET /', require('./routes/index'))
patterns.add('GET /posts', require('./routes/posts').index)
patterns.add('GET /posts/{id}', require('./routes/posts').show)

http.createServer(function (req, res) {
  // Check if we have a route matching the incoming request
  var match = patterns.match(req.method + ' ' + req.url);

  // If no match is found, respond with a 404. Elastic APM will in
  // this case use the default transaction name "unknown route"
  if (!match) {
    res.writeHead(404)
    res.end()
    return
  }

  // The patterns module exposes the pattern used to match the
  // request on the `pattern` property, e.g. `GET /posts/{id}`
  apm.setTransactionName(match.pattern)

  // Populate the params and call the matching route handler
  var fn = match.value
  req.params = match.params
  fn(req, res)
}).listen(3000)
----

[float]
[[custom-stack-unknown-routes]]
===== Unknown routes

include::./shared-set-up.asciidoc[tag=unknown-roots]

[float]
[[custom-stack-error-logging]]
==== Error logging

include::./shared-set-up.asciidoc[tag=error-logging]

[float]
[[custom-stack-middleware-error-handler]]
===== Middleware error handler

If you use the https://www.npmjs.com/package/connect[connect] module and an error is either thrown synchronously inside one of the middleware functions or is passed as the first argument to the middleware `next()` function,
it will be passed to the https://www.npmjs.com/package/connect#error-middleware[Connect error handler].

It's recommended that you register the agent as a Connect error handler.
In the case where you have multiple Connect error handlers,
the agent error handler should be the first in the chain to ensure that it will receive the error correctly.

[source,js]
----
var apm = require('elastic-apm-node').start()
var connect = require('connect')

var app = connect()

// Your regular middleware and router...
app.use(...)
app.use(...)
app.use(...)

// Add the Elastic APM middleware after your regular middleware
app.use(apm.middleware.connect())

// ...but before any other error handler
app.use(function (err, req, res, next) {
  // Custom error handling goes here
})
----

[float]
[[custom-stack-filter-sensitive-information]]
==== Filter sensitive information

include::./shared-set-up.asciidoc[tag=filter-sensitive-info]

[float]
[[custom-stack-add-your-own-data]]
==== Add your own data

include::./shared-set-up.asciidoc[tag=add-your-own-data]

[float]
[[custom-stack-compatibility]]
==== Compatibility

include::./shared-set-up.asciidoc[tag=compatibility-link]

[float]
[[custom-stack-troubleshooting]]
==== Troubleshooting

include::./shared-set-up.asciidoc[tag=troubleshooting-link]
