:framework: Express

[[express]]

ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/nodejs/current/express.html[elastic.co]
endif::[]

=== Get started with Express

Getting Elastic APM set up for your Express app is easy,
and there are various ways you can tweak it to fit your needs.
Follow the guide below to get started, and for more advanced topics,
check out the <<api>>.

[float]
[[express-installation]]
==== Installation

Add the `elastic-apm-node` module as a dependency to your application:

[source,bash]
----
npm install elastic-apm-node --save
----

[float]
[[express-initialization]]
==== Initialization

It's important that the agent is started before you require *any* other modules in your Node.js application - i.e. before `express`, `http`, etc.

This means that you should probably require and start the agent in your application's main file (usually `index.js`, `server.js` or `app.js`).

Here's a simple Express example with the Elastic APM agent installed:

[source,js]
----
// Add this to the VERY top of the first file loaded in your app
const apm = require('elastic-apm-node').start({
  // Override service name from package.json
  // Allowed characters: a-z, A-Z, 0-9, -, _, and space
  serviceName: '',

  // Use if APM Server requires a token
  secretToken: '',

  // Use if APM Server uses API keys for authentication
  apiKey: '',

  // Set custom APM Server URL (default: http://localhost:8200)
  serverUrl: '',
})

const app = require('express')()

app.get('/', function (req, res) {
  res.send('Hello World!')
})

app.listen(3000)
----

The agent will now monitor the performance of your Express application and record any uncaught exceptions.

[float]
[[express-advanced-configuration]]
===== Advanced configuration

include::./shared-set-up.asciidoc[tag=advanced-configuration]

[float]
[[express-full-documentation]]
===== Full documentation

* <<advanced-setup,Setup and Configuration>>
* <<api,API Reference>>

[float]
[[express-performance-monitoring]]
==== Performance monitoring

include::./shared-set-up.asciidoc[tag=performance-monitoring]

[float]
[[express-unknown-routes]]
===== Unknown routes

include::./shared-set-up.asciidoc[tag=unknown-roots]

[float]
[[express-error-logging]]
==== Error logging

include::./shared-set-up.asciidoc[tag=error-logging]

[float]
[[express-filter-sensitive-information]]
==== Filter sensitive information

include::./shared-set-up.asciidoc[tag=filter-sensitive-info]

[float]
[[express-add-your-own-data]]
==== Add your own data

include::./shared-set-up.asciidoc[tag=add-your-own-data]

[float]
[[express-compatibility]]
==== Compatibility

include::./shared-set-up.asciidoc[tag=compatibility-link]

[float]
[[express-troubleshooting]]
==== Troubleshooting

include::./shared-set-up.asciidoc[tag=troubleshooting-link]
