:framework: hapi

[[hapi]]

ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/nodejs/current/hapi.html[elastic.co]
endif::[]

=== Get started with hapi

include::./shared-set-up.asciidoc[tag=introduction]

[float]
[[hapi-installation]]
==== Installation

Add the `elastic-apm-node` module as a dependency to your application:

[source,bash]
----
npm install elastic-apm-node --save
----

[float]
[[hapi-initialization]]
==== Initialization

It's important that the agent is started before you require *any* other modules in your Node.js application - i.e. before `hapi`, `http`, etc.

This means that you should probably require and start the agent in your application's main file (usually `index.js`, `server.js` or `app.js`).

Here's a simple hapi example with the Elastic APM agent installed:

[source,js]
----
// Add this to the VERY top of the first file loaded in your app
const apm = require('elastic-apm-node').start({
  // Override service name from package.json
  // Allowed characters: a-z, A-Z, 0-9, -, _, and space
  serviceName: '',

  // Use if APM Server requires a token
  secretToken: '',

  // Use if APM Server uses API keys for authentication
  apiKey: '',

  // Set custom APM Server URL (default: http://localhost:8200)
  serverUrl: '',
})

const Hapi = require('@hapi/hapi')

const init = async () => {
  const server = Hapi.server({ port: 3000, host: 'localhost' })

  server.route({
    method: 'GET',
    path: '/',
    handler: (request, h) => {
      return 'hello world'
    }
  })

  await server.start()
  console.log('Server running on %s', server.info.uri)
}

init()
----

The agent will now monitor the performance of your hapi application and record any uncaught exceptions.

[float]
[[hapi-advanced-configuration]]
===== Advanced configuration

include::./shared-set-up.asciidoc[tag=advanced-configuration]

[float]
[[hapi-full-documentation]]
===== Full documentation

* <<advanced-setup,Setup and Configuration>>
* <<api,API Reference>>

[float]
[[hapi-performance-monitoring]]
==== Performance monitoring

include::./shared-set-up.asciidoc[tag=performance-monitoring]

[float]
[[hapi-unknown-routes]]
===== Unknown routes

include::./shared-set-up.asciidoc[tag=unknown-roots]

[float]
[[hapi-error-logging]]
==== Error logging

include::./shared-set-up.asciidoc[tag=error-logging]

[float]
[[hapi-filter-sensitive-information]]
==== Filter sensitive information

include::./shared-set-up.asciidoc[tag=filter-sensitive-info]

[float]
[[hapi-add-your-own-data]]
==== Add your own data

include::./shared-set-up.asciidoc[tag=add-your-own-data]

[float]
[[hapi-compatibility]]
==== Compatibility

include::./shared-set-up.asciidoc[tag=compatibility-link]

[float]
[[hapi-troubleshooting]]
==== Troubleshooting

include::./shared-set-up.asciidoc[tag=troubleshooting-link]
