[[intro]]
== Introduction

Welcome to the APM Node.js Agent documentation.

NOTE: The documentation pages are still work in progress.
For more details also check the APM Node.js Agent https://github.com/elastic/apm-agent-nodejs[GitHub repository].

The Elastic APM Node.js agent sends performance metrics and errors to the APM Server.
It has built-in support for the most popular frameworks and routers,
as well as a simple API which allows you to instrument any application.
The agent is only one of multiple components you need to get started with APM.
Please also have a look at the documentation for

* {apm-server-ref}/index.html[APM Server]
* {ref}/index.html[Elasticsearch]

[[getting-started]]
=== Getting started

To get you off the ground, we've prepared guides for the most popular web frameworks:

* <<express,Get started with Express>>
* <<hapi,Get started with hapi>>
* <<koa,Get started with Koa>>

Alternatively you should check out our guide for <<custom-stack,getting started with a custom Node.js stack>>.

Other useful documentation include:

- <<advanced-setup,Advanced Setup and Configuration>>
- <<api,API reference>>
- <<troubleshooting,Troubleshooting>>
