[[intro]]

ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/nodejs/current/intro.html[elastic.co]
endif::[]

== Introduction

Welcome to the APM Node.js Agent documentation.

The Elastic APM Node.js Agent sends performance metrics and errors to the APM Server.
It has built-in support for the most popular frameworks and routers,
as well as a simple API which allows you to instrument any application.
The agent is only one of multiple components you need to get started with APM.
Please also have a look at the documentation for

* {apm-server-ref}/index.html[APM Server]
* {ref}/index.html[Elasticsearch]

[float]
[[get-started]]
=== Get started

To get you off the ground, we've prepared guides for the most popular web frameworks:

* <<express,Get started with Express>>
* <<hapi,Get started with hapi>>
* <<koa,Get started with Koa>>
* <<restify,Get started with Restify>>

Alternatively you should check out our guide for <<custom-stack,getting started with a custom Node.js stack>>.
To get an overview over which components of your application we instrument automatically,
use the <<supported-technologies,Supported Technologies Overview>> page.

Other useful documentation include:

- <<advanced-setup,Advanced Setup and Configuration>>
- <<api,API reference>>
- <<troubleshooting,Troubleshooting>>
