[[intro]]

ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/nodejs/current/intro.html[elastic.co]
endif::[]

== Introduction

The Elastic APM Node.js Agent sends performance metrics and errors to the APM Server.
It has built-in support for the most popular frameworks and routers,
as well as a simple API which allows you to instrument any application.

[float]
[[how-it-works]]
=== How does the Agent work?

The agent auto-instruments <<compatibility-frameworks,supported frameworks>> and records interesting events,
like HTTP requests and database queries. To do this, it patches modules as they are loaded to capture when module functions and callbacks are called. Additionally, there are some cases where a module will be patched to allow tracing context to be propagated through the asynchronous continuation.
This means that for the supported technologies, there are no code changes required.

The Agent automatically links module function calls to callback calls to measure their duration and metadata (like the DB statement),
as well as HTTP related information (like the URL, parameters, and headers).

These events, called Transactions and Spans, are sent to the APM Server.
The APM Server converts them to a format suitable for Elasticsearch, and sends them to an Elasticsearch cluster.
You can then use the APM app in Kibana to gain insight into latency issues and error culprits within your application.

[float]
[[additional-components]]
=== Additional Components

APM Agents work in conjunction with the {apm-guide-ref-v}/index.html[APM Server], {ref}/index.html[Elasticsearch], and {kibana-ref}/index.html[Kibana].
The {apm-guide-ref}/index.html[APM Overview] provides details on how these components work together,
and provides a matrix outlining {apm-guide-ref}/agent-server-compatibility.html[Agent and Server compatibility].
