:framework: Koa

[[koa]]

ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/nodejs/current/koa.html[elastic.co]
endif::[]

=== Get started with Koa

include::./shared-set-up.asciidoc[tag=introduction]

Koa doesn't have a built-in router,
so we can't support Koa directly since we rely on router information for full support.
We currently support the most popular Koa router called https://github.com/koajs/koa-router[koa-router].

If you use another router with your Koa application,
please https://github.com/elastic/apm-agent-nodejs/issues[open an issue] so we can make sure to support your stack.
In the meantime, you can <<custom-stack,configure Elastic APM to work with any stack>>.

[float]
[[koa-installation]]
==== Installation

Add the `elastic-apm-node` module as a dependency to your application:

[source,bash]
----
npm install elastic-apm-node --save
----

[float]
[[koa-initialization]]
==== Initialization

It's important that the agent is started before you require *any* other modules in your Node.js application - i.e. before `koa`, `http`, etc.

This means that you should probably require and start the agent in your application's main file (usually `index.js`, `server.js` or `app.js`).

Here's a simple Koa example with the Elastic APM agent installed:

[source,js]
----
// Add this to the VERY top of the first file loaded in your app
const apm = require('elastic-apm-node').start({
  // Override service name from package.json
  // Allowed characters: a-z, A-Z, 0-9, -, _, and space
  serviceName: '',

  // Use if APM Server requires a token
  secretToken: '',

  // Use if APM Server uses API keys for authentication
  apiKey: '',

  // Set custom APM Server URL (default: http://127.0.0.1:8200)
  serverUrl: '',
})

const app = require('koa')()
const router = require('koa-router')()

router.get('/', function *(next) {
  this.body = 'Hello World'
})

app
  .use(router.routes())
  .use(router.allowedMethods())

app.listen(3000)
----

The agent will now monitor the performance of your Koa application and record any uncaught exceptions.

[float]
[[koa-advanced-configuration]]
===== Advanced configuration

include::./shared-set-up.asciidoc[tag=advanced-configuration]

[float]
[[koa-full-documentation]]
===== Full documentation

* <<advanced-setup,Setup and Configuration>>
* <<api,API Reference>>

[float]
[[koa-performance-monitoring]]
==== Performance monitoring

include::./shared-set-up.asciidoc[tag=performance-monitoring]

[float]
[[koa-unknown-routes]]
===== Unknown routes

include::./shared-set-up.asciidoc[tag=unknown-roots]

[float]
[[koa-error-logging]]
==== Error logging

include::./shared-set-up.asciidoc[tag=error-logging]

[float]
[[koa-filter-sensitive-information]]
==== Filter sensitive information

include::./shared-set-up.asciidoc[tag=filter-sensitive-info]

[float]
[[koa-add-your-own-data]]
==== Add your own data

include::./shared-set-up.asciidoc[tag=add-your-own-data]

[float]
[[koa-compatibility]]
==== Compatibility

include::./shared-set-up.asciidoc[tag=compatibility-link]

[float]
[[koa-troubleshooting]]
==== Troubleshooting

include::./shared-set-up.asciidoc[tag=troubleshooting-link]
