:framework: lambda

[[lambda]]

ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/nodejs/current/lambda.html[elastic.co]
endif::[]

=== Get started with Lambda (Deprecated)

WARNING: *Lambda functions are no longer supported by the Elastic APM Node.js Agent.*

Getting Elastic APM set up for your lambda functions is easy,
and there are various ways you can tweak it to fit your needs.
Follow the guide below to get started, and for more advanced topics,
check out the <<api,API Reference>>.

[float]
[[lambda-installation]]
==== Installation

Add the `elastic-apm-node` module as a dependency to your application:

[source,bash]
----
npm install elastic-apm-node --save
----

[float]
[[lambda-initialization]]
==== Initialization

It's important that the agent is started before you require *any* other modules in your Node.js application - i.e. before `http`, etc.

Here's a simple lambda example with the Elastic APM agent installed:

[source,js]
----
// Add this to the VERY top of the first file loaded in your app
const apm = require('elastic-apm-node').start({
  // Override service name from package.json
  // Allowed characters: a-z, A-Z, 0-9, -, _, and space
  serviceName: '',

  // Use if APM Server requires a token
  secretToken: '',

  // Use if APM Server uses API keys for authentication
  apiKey: '',

  // Set custom APM Server URL (default: http://localhost:8200)
  serverUrl: '',
})

exports.handler = apm.lambda(function handler (payload, context, callback) {
  callback(null, `Hello, ${payload.name}!`)
})
----

The agent will now monitor the performance of your lambda function.

[float]
[[lambda-full-documentation]]
===== Full documentation

* <<advanced-setup,Setup and Configuration>>
* <<api,API Reference>>

[float]
[[lambda-performance-monitoring]]
==== Performance monitoring

Elastic APM automatically measures the performance of everything within your lambda function executions.
It records traces for database queries,
external HTTP requests,
and other slow operations that happen during execution.

By default, the agent will trace <<supported-technologies,the most common modules>>.
To trace other events,
you can use custom traces.
For information about custom traces,
see the <<custom-spans,Custom Spans section>>.

[float]
[[lambda-error-logging]]
==== Error logging

include::./shared-set-up.asciidoc[tag=error-logging]

[float]
[[lambda-filter-sensitive-information]]
==== Filter sensitive information

include::./shared-set-up.asciidoc[tag=filter-sensitive-info]

[float]
[[lambda-add-your-own-data]]
==== Add your own data

The Node.js agent will keep track of the active lambda function execution and will link it to errors and recorded transaction metrics when they are sent to the Elastic APM server.
This allows you to see details about which execution resulted in a particular error or which lambda functions are slow.

But in many cases,
information about the lambda execution itself isn't enough.
To add even more metadata to errors and transactions,
use one of the two functions below:

* <<apm-set-user-context,`apm.setUserContext()`>> - Call this to enrich collected performance data and errors with information about the user/client
* <<apm-set-custom-context,`apm.setCustomContext()`>> - Call this to enrich collected performance data and errors with any information that you think will help you debug performance issues and errors (this data is only stored, but not indexed in Elasticsearch)
* <<apm-set-label,`apm.setLabel()`>> - Call this to enrich collected performance data and errors with simple key/value strings that you think will help you debug performance issues and errors (labels are indexed in Elasticsearch)

[float]
[[lambda-troubleshooting]]
==== Troubleshooting

include::./shared-set-up.asciidoc[tag=troubleshooting-link]
