[[metrics]]

ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/nodejs/current/metrics.html[elastic.co]
endif::[]

== Metrics

The Node.js agent tracks various system and application metrics.
These metrics will be sent regularly to the APM Server and from there to Elasticsearch.
You can adjust the interval by setting <<metrics-interval,`metricsInterval`>>.

The metrics will be stored in the `apm-*` index and have the `processor.event` property set to `metric`.

[float]
[[metric-system.cpu.total.norm.pct]]
=== `system.cpu.total.norm.pct`

* *Type:* Float
* *Format:* Percent

The percentage of CPU time in states other than Idle and IOWait,
normalized by the number of cores.

[float]
[[metric-system.memory.total]]
=== `system.memory.total`

* *Type:* Long
* *Format:* Bytes

The total memory of the system in bytes.

[float]
[[metric-system.memory.actual.free]]
=== `system.memory.actual.free`

* *Type:* Long
* *Format:* Bytes

Free memory of the system in bytes.

[float]
[[metric-system.process.cpu.total.norm.pct]]
=== `system.process.cpu.total.norm.pct`

* *Type:* Float
* *Format:* Percent

The percentage of CPU time spent by the process since the last event.
This value is normalized by the number of CPU cores and it ranges from 0 to 100%.

[float]
[[metric-system.process.memory.rss.bytes]]
=== `system.process.memory.rss.bytes`

* *Type:* Long
* *Format:* Bytes

The Resident Set Size,
the amount of memory the process occupies in main memory (RAM).

[float]
[[metric-nodejs.active_handles]]
=== `nodejs.active_handles`

* *Type:* Long
* *Format:* Counter

The number of active libuv handles,
likely held open by currently running I/O operations.

[float]
[[metric-nodejs.active_requests]]
=== `nodejs.active_requests`

* *Type:* Long
* *Format:* Counter

The number of active libuv requests,
likely waiting for a response to an I/O operation.

[float]
[[metric-nodejs.cpu.user]]
=== `nodejs.cpu.user`

* *Type:* Long
* *Format:* Counter

The number of CPU cycles spent executing application code.

[float]
[[metric-nodejs.cpu.system]]
=== `nodejs.cpu.system`

* *Type:* Long
* *Format:* Counter

The number of CPU cycles spent executing kernel code as a result of application activity.

[float]
[[metric-nodejs.loop.delay]]
=== `nodejs.loop.delay`

* *Type:* Float
* *Format:* Milliseconds

The number of milliseconds of event loop delay.

[float]
[[metric-nodejs.loop.times]]
=== `nodejs.loop.times`

* *Type:* Long
* *Format:* Counter

The number of times event loop delay was detected.

[float]
[[metric-nodejs.heap.allocated]]
=== `nodejs.heap.allocated`

* *Type:* Long
* *Format:* Bytes

The current allocated heap size in bytes.

[float]
[[metric-nodejs.heap.used]]
=== `nodejs.heap.used`

* *Type:* Long
* *Format:* Bytes

The currently used heap size in bytes.
