[[metrics]]

ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/nodejs/current/metrics.html[elastic.co]
endif::[]

== Metrics

The Node.js agent tracks various system and application metrics.
These metrics will be sent regularly to the APM Server and from there to Elasticsearch.
You can adjust the interval by setting <<metrics-interval,`metricsInterval`>>.

The metrics will be stored in the `apm-*` index and have the `processor.event` property set to `metric`.

[float]
[[metric-system.cpu.total.norm.pct]]
=== `system.cpu.total.norm.pct`

* *Type:* Float
* *Format:* Percent

The percentage of CPU time in states other than Idle and IOWait,
normalized by the number of cores.

[float]
[[metric-system.memory.total]]
=== `system.memory.total`

* *Type:* Long
* *Format:* Bytes

The total memory of the system in bytes.

[float]
[[metric-system.memory.actual.free]]
=== `system.memory.actual.free`

* *Type:* Long
* *Format:* Bytes

Free memory of the system in bytes.

[float]
[[metric-system.process.cpu.total.norm.pct]]
=== `system.process.cpu.total.norm.pct`

* *Type:* Float
* *Format:* Percent

The percentage of CPU time spent by the process since the last event.
This value is normalized by the number of CPU cores and it ranges from 0 to 100%.

[float]
[[metric-system.process.memory.rss.bytes]]
=== `system.process.memory.rss.bytes`

* *Type:* Long
* *Format:* Bytes

The Resident Set Size,
the amount of memory the process occupies in main memory (RAM).

[float]
[[metric-nodejs.handles.active]]
=== `nodejs.handles.active`

* *Type:* Long
* *Format:* Counter

The number of active libuv handles,
likely held open by currently running I/O operations.

[float]
[[metric-nodejs.requests.active]]
=== `nodejs.requests.active`

* *Type:* Long
* *Format:* Counter

The number of active libuv requests,
likely waiting for a response to an I/O operation.

[float]
[[metric-system.process.cpu.user.norm.pct]]
=== `system.process.cpu.user.norm.pct`

* *Type:* Long
* *Format:* Counter

The number of CPU cycles spent executing application code.

[float]
[[metric-system.process.cpu.system.norm.pct]]
=== `system.process.cpu.system.norm.pct`

* *Type:* Long
* *Format:* Counter

The number of CPU cycles spent executing kernel code as a result of application activity.

[float]
[[metric-nodejs.eventloop.delay.avg.ms]]
=== `nodejs.eventloop.delay.avg.ms`

* *Type:* Float
* *Format:* Milliseconds

The number of milliseconds of event loop delay.
Event loop delay is sampled every 10 milliseconds.
Delays shorter than 10ms may not be observed,
for example if a blocking operation starts and ends within the same sampling period.

[float]
[[metric-nodejs.memory.heap.allocated.bytes]]
=== `nodejs.memory.heap.allocated.bytes`

* *Type:* Long
* *Format:* Bytes

The current allocated heap size in bytes.

[float]
[[metric-nodejs.memory.heap.used.bytes]]
=== `nodejs.memory.heap.used.bytes`

* *Type:* Long
* *Format:* Bytes

The currently used heap size in bytes.

[float]
[[metric-nodejs.memory.external.bytes]]
=== `nodejs.memory.external.bytes`

* *Type:* Long
* *Format:* Bytes

Memory usage of C++ objects bound to JavaScript objects managed by V8.

[float]
[[metric-nodejs.memory.arrayBuffers.bytes]]
=== `nodejs.memory.arrayBuffers.bytes`

* *Type:* Long
* *Format:* Bytes

Memory allocated for ArrayBuffers and SharedArrayBuffers, including all Node.js Buffers.
This is also included in the `nodejs.memory.external.bytes` value.

[float]
[[metrics-span.self_time.sum]]
=== `span.self_time.sum`

* *Type:* Long
* *Format:* Milliseconds

The sum of all span self-times in milliseconds since the last report (the delta).
The `span.self_time.*` metrics are referred to as "breakdown metrics".

You can filter and group by these dimensions:

* `transaction.name`: The name of the transaction
* `transaction.type`: The type of the transaction, for example `request`
* `span.type`: The type of the span, for example `app`, `template` or `db`
* `span.subtype`: The sub-type of the span, for example `mysql` (optional)

[float]
[[metrics-span.self_time.count]]
=== `span.self_time.count`

* *Type:* Long
* *Format:* Counter

You can filter and group by these dimensions:

* `transaction.name`: The name of the transaction
* `transaction.type`: The type of the transaction, for example `request`
* `span.type`: The type of the span, for example `app`, `template` or `db`
* `span.subtype`: The sub-type of the span, for example `mysql` (optional)
