[[advanced-setup]]

ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/nodejs/current/advanced-setup.html[elastic.co].
endif::[]

== Configuration

Use the following pages to configure the APM Agent.

* <<configuring-the-agent>>
** <<agent-configuration-object>>
** <<agent-configuration-file>>
* <<configuration>>

[[configuring-the-agent]]
=== Configuring the agent

There are multiple ways to configure the Node.js agent. In order of precedence:

1. APM Agent Central Configuration via Kibana.
(supported options are marked with <<dynamic-configuration, image:./images/dynamic-config.svg[] >>)

2. Environment variables.

3. If calling the `apm.start()` function, supply a <<agent-configuration-object,configurations object>> as the first argument.

4. Via the <<agent-configuration-file,agent configuration file>>.

For information on the available configuration properties and the expected names of environment variables, see the <<configuration,Configuration options>> documentation.

[float]
[[dynamic-configuration]]
==== Dynamic configuration

Configuration options marked with the image:./images/dynamic-config.svg[] badge can be changed at runtime
when set from a supported source.

The Node.js Agent supports {apm-app-ref}/agent-configuration.html[Central configuration],
which allows you to fine-tune certain configurations via the APM app in Kibana.
This feature is enabled in the Agent by default, with <<central-config>>.

[float]
[[agent-configuration-object]]
==== Agent configuration object

To use the optional `options` argument, pass it into the `apm.start()` method:

[source,js]
----
var apm = require('elastic-apm-node').start({
  // add configuration options here
})
----

This example shows how to configure the agent to only be active in production:

[source,js]
----
// Add this to the VERY top of the first file loaded in your app
require('elastic-apm-node').start({
  // Override service name from package.json
  // Allowed characters: a-z, A-Z, 0-9, -, _, and space
  serviceName: '',

  // Use if APM Server requires a token
  secretToken: '',

  // Use if APM Server uses API keys for authentication
  apiKey: '',

  // Set custom APM Server URL (default: http://localhost:8200)
  serverUrl: '',

  // Only activate the agent if it's running in production
  active: process.env.NODE_ENV === 'production'
})
----

[float]
[[agent-configuration-file]]
==== Agent configuration file

The Node.js agent looks for a file named `elastic-apm-node.js` in the current working directory.
You can specify a custom path for this file with the <<config-file,`configFile`>> configuration option.


include::./configuration.asciidoc[]

include::./custom-transactions.asciidoc[]

include::./custom-spans.asciidoc[]
