[[transaction-api]]

ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/nodejs/current/transaction-api.html[elastic.co]
endif::[]

=== `Transaction` API

A transaction groups multiple spans in a logical group.

To get a `Transaction` object,
you need to call <<apm-start-transaction,`apm.startTransaction()`>>.

To see an example of using custom transactions,
see the <<custom-transactions,Custom Transactions in Node.js>> article.

[[transaction-name]]
==== `transaction.name`

[small]#Added in: v0.1.0#

* +{type-string}+ *Default:* `unnamed`

The name of the transaction.

Can be used to set or overwrite the name of the transaction (visible in the performance monitoring breakdown).
If you don't have access to the current transaction,
you can also set the name using <<apm-set-transaction-name,`apm.setTransactionName()`>>.

Transactions with the same name and <<transaction-type,type>> are grouped together.

[[transaction-type]]
==== `transaction.type`

[small]#Added in: v0.1.0#

[small]#Split components into `type`, `subtype` and `action` in: v3.0.0#

* +{type-string}+ *Default:* `custom`

The type of the transaction.

There's a special type called `request` which is used by the agent for the transactions automatically created when an incoming HTTP request is detected.

[[transaction-subtype]]
==== `transaction.subtype` deprecated:[v3.25.0]

[small]#Added in: v3.0.0# +
[small]#Deprecated in: v3.25.0#

* +{type-string}+ *Default:* `custom`

The subtype of the transaction.
The transaction `subtype` field is deprecated: it is not used and will be
removed in the next major version.

[[transaction-action]]
==== `transaction.action` deprecated:[v3.25.0]

[small]#Added in: v3.0.0# +
[small]#Deprecated in: v3.25.0#

* +{type-string}+ *Default:* `custom`

The action of the transaction.
The transaction `action` field is deprecated: it is not used and will be removed
in the next major version.

[[transaction-traceparent]]
==== `transaction.traceparent`

[small]#Added in: v2.9.0#

Get the serialized traceparent string of the transaction.

[[transaction-result]]
==== `transaction.result`

[small]#Added in: v0.1.0#

* +{type-string}+ *Default:* `success`

A string describing the result of the transaction.
This is typically the HTTP status code,
or e.g. "success" or "failure" for a background task.

[[transaction-start-span]]
==== `transaction.startSpan([name][, type][, subtype][, action][, options])`

[small]#Added in: v2.0.0#

[small]#Split `type` into `type`, `subtype` and `action` in: v3.0.0#

* `name` +{type-string}+ The name of the span.
You can alternatively set this via <<span-name,`span.name`>>.
*Default:* `unnamed`

* `type` +{type-string}+ The type of the span.
You can alternatively set this via <<span-type,`span.type`>>.

* `subtype` +{type-string}+ The subtype of the span.
You can alternatively set this via <<span-subtype,`span.subtype`>>.

* `action` +{type-string}+ The action of the span.
You can alternatively set this via <<span-action,`span.action`>>.

* `options` - The following options are supported:

** `startTime` +{type-number}+ The time when the span started.
Must be a Unix Time Stamp representing the number of milliseconds since January 1, 1970, 00:00:00 UTC.
Sub-millisecond precision can be achieved using decimals.
If not provided,
the current time will be used

** `exitSpan` +{type-boolean}+ Make an "exit span".
Exit spans represent outgoing communication. They are used to create a node
in the {kibana-ref}/service-maps.html[Service Map] and a downstream service
in the {kibana-ref}/dependencies.html[Dependencies Table]. The provided subtype
will be used as the downstream service name.

** `links` +{type-array}+ Span links.
A span can refer to zero or more other transactions or spans (separate from
its parent). Span links will be shown in the Kibana APM app trace view. The
`links` argument is an array of objects with a single "context" field that is a
`Transaction`, `Span`, or W3C trace-context 'traceparent' string.  For example:
`transaction.startSpan('aName', { links: [{ context: anotherSpan }] })`.

Start and return a new custom span associated with this transaction.
When a span is started it will measure the time until <<span-end,`span.end()`>> is called.

See <<span-api,Span API>> docs for details on how to use custom spans.

[[transaction-set-label]]
==== `transaction.setLabel(name, value[, stringify = true])`

[small]#Added in: v0.1.0# +
[small]#Renamed from `transaction.setTag()` to `transaction.setLabel()`: v2.10.0# +
[small]#Added `stringify` argument in: v3.11.0#

* `name` +{type-string}+
Any periods (`.`), asterisks (`*`), or double quotation marks (`"`) will be replaced by underscores (`_`),
as those characters have special meaning in Elasticsearch
* `value` +{type-string}+ | +{type-number}+ | +{type-boolean}+
* `stringify` +{type-boolean}+
Defaults to `true`. When true, if a non-string `value` is given, it is
converted to a string before being sent to the APM Server

Set a label on the transaction.
You can set multiple labels on the same transaction.
If an error happens during the transaction,
it will also get tagged with the same labels.

Tags are key/value pairs that are indexed by Elasticsearch and therefore searchable (as opposed to data set via <<apm-set-custom-context,`apm.setCustomContext()`>>).

[[transaction-add-labels]]
==== `transaction.addLabels({ [name]: value }[, stringify = true])`

[small]#Added in: v1.5.0# +
[small]#Renamed from `transaction.addTags()` to `transaction.addLabels()`: v2.10.0# +
[small]#Added `stringify` argument in: v3.11.0#

* `labels` +{type-object}+ Contains key/value pairs:
** `name` +{type-string}+
Any periods (`.`), asterisks (`*`), or double quotation marks (`"`) will be replaced by underscores (`_`),
as those characters have special meaning in Elasticsearch
** `value` +{type-string}+ | +{type-number}+ | +{type-boolean}+
* `stringify` +{type-boolean}+
Defaults to `true`. When true, if a non-string `value` is given, it is
converted to a string before being sent to the APM Server.

Add several labels on the transaction.
You can add labels multiple times.
If an error happens during the transaction,
it will also get tagged with the same labels.

Labels are key/value pairs that are indexed by Elasticsearch and therefore searchable (as opposed to data set via <<apm-set-custom-context,`apm.setCustomContext()`>>).

[[transaction-ensure-parent-id]]
==== `transaction.ensureParentId()`

[small]#Added in: v2.0.0#

* +{type-string}+

If the transaction does not already have a parent id,
calling this method generates a new parent id,
sets it as the parent id of this transaction,
and returns it as a +{type-string}+.

This enables the correlation of the spans the JavaScript Real User Monitoring (RUM) agent creates for the initial page load with the transaction of the backend service.
If your backend service generates the HTML page dynamically,
initializing the JavaScript RUM agent with the value of this method allows analyzing the time spent in the browser vs in the backend services.

// WARNING: The below content is reused in distributed-tracing.asciidoc
// Ensure any changes made here are safe to include on that page as well.
// tag::ensure-parent-id-snippet[]
To enable the JavaScript RUM agent,
add a snippet similar to this to the body of your HTML page,
preferably before other JavaScript libraries:

[source,js]
----
elasticApm.init({
  serviceName: 'my-frontend-app', // Name of your frontend app
  serverUrl: 'https://example.com:8200', // APM Server host
  pageLoadTraceId: '${transaction.traceId}',
  pageLoadSpanId: '${transaction.ensureParentId()}',
  pageLoadSampled: ${transaction.sampled}
})
----
// end::ensure-parent-id-snippet[]

See the {apm-rum-ref}[JavaScript RUM agent documentation] for more information.

[[transaction-ids]]
==== `transaction.ids`

[small]#Added in: v2.17.0#

Produces an object containing `transaction.id` and `trace.id`.
This enables log correlation to APM traces with structured loggers.

[source,js]
----
{
  "trace.id": "abc123",
  "transaction.id": "abc123"
}
----


[[transaction-to-string]]
==== `transaction.toString()` deprecated:[v3.23.0]

[small]#Added in: v2.17.0# +
[small]#Deprecated in: v3.23.0#

Produces a string representation of the transaction to inject in log messages.
This enables log correlation to APM traces with text-only loggers.

[source,js]
----
"trace.id=abc123 transaction.id=abc123"
----

Relying on the format of `transaction.toString()` has been **deprecated** and may
change in v4 of the agent. Prefer the use of <<transaction-ids,`transaction.ids`>> or
<<apm-current-trace-ids,`apm.currentTraceIds`>>. The v3 format may be reproduced
via:

[source,js]
----
const { stringify } = require('querystring')
console.log( stringify(transaction.ids, ' ', '=')) )
----


[[transaction-end]]
==== `transaction.end([result][, endTime])`

[small]#Added in: v0.1.0#

* `result` +{type-string}+ Describes the result of the transaction.
This is typically the HTTP status code,
or e.g. "success" or "failure" for a background task

* `endTime` +{type-number}+ The time when the transaction ended.
Must be a Unix Time Stamp representing the number of milliseconds since January 1, 1970, 00:00:00 UTC.
Sub-millisecond precision can be achieved using decimals.
If not provided,
the current time will be used

Ends the transaction.
If the transaction has already ended,
nothing happens.

Alternatively you can call <<apm-end-transaction,`apm.endTransaction()`>> to end the active transaction.

[[transaction-outcome]]
==== `transaction.outcome`

[small]#Added in: v3.12.0#

The Node.js agent automatically sets an `outcome` property on transactions.  This property will be one of three values:

- `success`: Indicates the transaction's operation was a success.

- `failure`: Indicates the transaction's operation was _not_ a success.

- `unknown`: Indicates we were unable to determine if the transaction's operation was a success or not.  An `unknown` outcome removes a transaction from error rate considerations.

A transaction is considered a success if the underlying HTTP request handling produces a response with a status code that is less than `500`.  A status code of `500` or greater is considered a failure.

Non-HTTP transactions will begin with an outcome of `unknown`.

[[transaction-setoutcome]]
==== `transaction.setOutcome(outcome)`

[small]#Added in: v3.12.0#

* `outcome` +{type-string}+

The `setOutcome` method allows an end user to override the Node.js agent's default setting of a transaction's `outcome` property.  The `setOutcome` method accepts a string of either `success`, `failure`, or `unknown`, and will force the agent to report this value for a specific span.
