[[upgrading]]

ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/nodejs/current/upgrading.html[elastic.co]
endif::[]

== Upgrading

The Elastic APM Node.js Agent uses https://semver.org/[semantic versioning], and therefore:

* Upgrades between minor versions of the agent, like from 1.1 to 1.2 are always backwards compatible.
* Upgrades that involve a major version bump often come with some backwards incompatible changes.

Before upgrading the agent, be sure to review the:

* <<release-notes,Node.js APM Agent release notes>>
* {apm-guide-ref}/agent-server-compatibility.html[APM Agent and Server compatibility chart]

The following upgrade guides are available:

* <<upgrade-to-v1,Upgrade to v1.x>> - Follow this guide to upgrade from version 0.x to version 1.x of the Elastic APM Node.js agent
* <<upgrade-to-v2,Upgrade to v2.x>> - Follow this guide to upgrade from version 1.x to version 2.x of the Elastic APM Node.js agent
* <<upgrade-to-v3,Upgrade to v3.x>> - Follow this guide to upgrade from version 2.x to version 3.x of the Elastic APM Node.js agent

[float]
[[end-of-life-dates]]
=== End of life dates

We love all our products, but sometimes we must say goodbye to a release so that we can continue moving
forward on future development and innovation.
Our https://www.elastic.co/support/eol[End of life policy] defines how long a given release is considered supported,
as well as how long a release is considered still in active development or maintenance.
The table below is a simplified description of this policy.

[options="header"]
|====
|Agent version |EOL Date |Maintained until
|3.33.x |2023-11-05 |3.34.0
|3.32.x |2023-10-27 |3.33.0
|3.31.x |2023-09-23 |3.32.0
|3.30.x |2023-09-10 |3.31.0
|3.29.x |2023-08-10 |3.30.0
|3.28.x |2023-08-08 |3.29.0
|3.27.x |2023-07-17 |3.28.0
|3.26.x |2023-06-07 |3.27.0
|3.25.x |2023-05-24 |3.26.0
|3.24.x |2023-05-09 |3.25.0
|3.23.x |2023-04-25 |3.24.0
|3.22.x |2023-04-21 |3.23.0
|3.21.x |2023-03-15 |3.22.0
|3.20.x |2023-02-12 |3.21.0
|3.19.x |2023-02-05 |3.20.0
|3.18.x |2023-01-20 |3.19.0
|3.17.x |2023-01-05 |3.18.0
|3.16.x |2022-12-14 |3.17.0
|3.15.x |2022-11-19 |3.16.0
|3.14.x |2022-10-19 |3.15.0
|3.13.x |2022-10-06 |3.14.0
|3.12.x |2022-08-22 |3.13.0
|3.11.x |2022-08-08 |3.12.0
|3.10.x |2022-07-11 |3.11.0
|3.9.x |2022-05-30 |3.10.0
|3.8.x |2022-05-09 |3.9.0
|3.7.x |2022-02-10 |3.8.0
|3.6.x |2021-11-18 |3.7.0
|3.5.x |2021-09-09 |3.6.0
|3.4.x |2021-08-21 |3.5.0
|3.3.x |2021-06-12 |3.4.0
|3.2.x |2021-05-18 |3.3.0
|3.1.x |2021-04-16 |3.2.0
|3.0.x |2021-03-30 |3.1.0
|2.17.x |2021-03-19 |(now EOL)
|1.14.x |2020-05-06 |(now EOL)
|====

include::./upgrade-to-v1.asciidoc[Upgrade to v1.x]

include::./upgrade-to-v2.asciidoc[Upgrade to v2.x]

include::./upgrade-to-v3.asciidoc[Upgrade to v3.x]
