[[upgrading]]

ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/nodejs/current/upgrading.html[elastic.co]
endif::[]

== Upgrading

The Elastic APM Node.js Agent uses https://semver.org/[semantic versioning], and therefore:

* Upgrades between minor versions of the agent, like from 1.1 to 1.2 are always backwards compatible.
* Upgrades that involve a major version bump often come with some backwards incompatible changes.

Before upgrading the agent, be sure to review the:

* <<release-notes,Node.js APM Agent release notes>>
* {apm-guide-ref}/agent-server-compatibility.html[APM Agent and Server compatibility chart]

The following upgrade guides are available:

* <<upgrade-to-v1,Upgrade to v1.x>> - Follow this guide to upgrade from version 0.x to version 1.x of the Elastic APM Node.js agent
* <<upgrade-to-v2,Upgrade to v2.x>> - Follow this guide to upgrade from version 1.x to version 2.x of the Elastic APM Node.js agent
* <<upgrade-to-v3,Upgrade to v3.x>> - Follow this guide to upgrade from version 2.x to version 3.x of the Elastic APM Node.js agent

[float]
[[end-of-life-dates]]
=== End of life dates

We love all our products, but sometimes we must say goodbye to a release so that we can continue moving
forward on future development and innovation.
Our https://www.elastic.co/support/eol[End of life policy] defines how long a given release is considered supported,
as well as how long a release is considered still in active development or maintenance.
The table below is a simplified description of this policy.

include::./upgrade-to-v1.asciidoc[Upgrade to v1.x]

include::./upgrade-to-v2.asciidoc[Upgrade to v2.x]

include::./upgrade-to-v3.asciidoc[Upgrade to v3.x]
