[[upgrade-to-v4]]

ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/nodejs/current/upgrade-to-v4.html[elastic.co]
endif::[]

=== Upgrade to v4.x

The following is a guide on upgrading your APM Node.js agent
(`elastic-apm-node`) from version 3.x to version 4.x.

[[v4-nodejs]]
==== Node.js versions

Version 4.0.0 of the Node.js APM agent supports Node.js v14.5.0 and later.

[[v4-config-options]]
==== Config options

Support for the following Kubernetes environment variables have been removed:
`ELASTIC_APM_KUBERNETES_NAMESPACE`, `ELASTIC_APM_KUBERNETES_NODE_NAME`,
`ELASTIC_APM_KUBERNETES_POD_NAME`, and `ELASTIC_APM_KUBERNETES_POD_UID`. The
correct environment variables for these config vars are **without** the
`ELASTIC_APM_` prefix -- for example
<<kubernetes-pod-name,`KUBERNETES_POD_NAME`>> -- and has been documented that
way since v2.11.0.

Support for `filterHttpHeaders` config option has been removed. Redaction of
HTTP headers and also request cookies is controlled by the existing config option
<<sanitize-field-names, `sanitizeFieldnames`>>.

[[v4-api-changes]]
==== API changes

XXX

