[[upgrade-to-v3]]

ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/nodejs/current/upgrade-to-v3.html[elastic.co]
endif::[]

=== Upgrade to v3.x

The following is a guide on upgrading your Node.js agent from version 2.x to version 3.x.

[[v3-overview]]
==== Overview

Version 3.0.0 of the Node.js agent supports Node.js v8 (from v8.6.0 and onwards), v10, and v12.

[[v3-config-options]]
==== Config options

The <<disable-instrumentations,`disableInstrumentations`>> config option now behaves differently if given the values `http` and/or `https`.
Previously this would disable tracing of incoming and outgoing requests.
Now this config option only deals with outgoing requests.
To disable tracing of incoming http(s) requests, use the new <<instrument-incoming-http-requests,`instrumentIncomingHTTPRequests`>> config option.

It's now possible to make use of manual instrumention while the <<instrument,`instrument`>> config option is set to `false`.
This means that calls to for instance <<apm-start-transaction,`apm.startTransaction()`>> or <<apm-start-span,`apm.startSpan()`>> will produce transactions and spans even if `instrument` is set to `false`.

[[v3-api-changes]]
==== API changes

The `type` associated with transactions and spans is no longer dot-separated.
Instead the `type` property has been split into three distinct properties: `type`, `subtype`, and `action`.
This has resulted in changes to the following API's:

- <<apm-start-transaction,`apm.startTransaction()`>>: Function arguments changed
- <<apm-start-span,`apm.startSpan()`>>: Function arguments changed
- <<transaction-start-span,`transaction.startSpan()`>>: Function arguments changed
- <<transaction-type,`transaction.type`>>: String format changed
- <<span-type,`span.type`>>: String format changed

The following deprecated API's has been removed:

- `apm.setTag()`: Replaced by <<apm-set-label,`apm.setLabel()`>>
- `apm.addTags()`: Replaced by <<apm-add-labels,`apm.addLabels()`>>
- `transaction.setTag()`: Replaced by <<transaction-set-label,`transaction.setLabel()`>>
- `transaction.addTags()`: Replaced by <<transaction-add-labels,`transaction.addLabels()`>>
- `span.setTag()`: Replaced by <<span-set-label,`span.setLabel()`>>
- `span.addTags()`: Replaced by <<span-add-labels,`span.addLabels()`>>

[[v3-changes-in-collected-data]]
==== Changes in collected data

When instrumenting a GraphQL server that is run by https://www.npmjs.com/package/apollo-server-express[`apollo-server-express`]
the Transaction type is now `graphql` instead of `request`.

All Spans whose type was previously `ext` is now `external`.
