[[upgrading]]

ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/nodejs/current/upgrading.html[elastic.co]
endif::[]

== Upgrading

The Elastic APM Node.js Agent uses https://semver.org/[semantic versioning], and therefore:

* Upgrades between minor versions of the agent, like from 1.1 to 1.2 are always backwards compatible.
* Upgrades that involve a major version bump often come with some backwards incompatible changes.

The following upgrade guides are available:

* <<upgrade-to-v1,Upgrade to v1.x>> - Follow this guide to upgrade from version 0.x to version 1.x of the Elastic APM Node.js agent
* <<upgrade-to-v2,Upgrade to v2.x>> - Follow this guide to upgrade from version 1.x to version 2.x of the Elastic APM Node.js agent
* <<upgrade-to-v3,Upgrade to v3.x>> - Follow this guide to upgrade from version 2.x to version 3.x of the Elastic APM Node.js agent

[float]
[[end-of-life-dates]]
=== End of life dates

We love all our products, but sometimes we must say goodbye to a release so that we can continue moving
forward on future development and innovation.
Our https://www.elastic.co/support/eol[End of life policy] defines how long a given release is considered supported,
as well as how long a release is considered still in active development or maintenance.
The table below is a simplified description of this policy.

[options="header"]
|====
|Agent version |EOL Date |Maintained until
|3.12.x |2022-08-22 |3.13.0
|3.11.x |2022-08-08 |3.12.0
|3.10.x |2022-07-11 |3.11.0
|3.9.x |2022-05-30 |3.10.0
|3.8.x |2022-05-09 |3.9.0
|3.7.x |2022-02-10 |3.8.0
|3.6.x |2021-11-18 |3.7.0
|3.5.x |2021-09-09 |3.6.0
|3.4.x |2021-08-21 |3.5.0
|3.3.x |2021-06-12 |3.4.0
|3.2.x |2021-05-18 |3.3.0
|3.1.x |2021-04-16 |3.2.0
|3.0.x |2021-03-30 |3.1.0
|2.17.x |2021-03-19 |4.0.0
|2.16.x |2021-02-26 |2.17.0
|2.15.x |2021-02-15 |2.16.0
|2.14.x |2021-02-12 |2.15.0
|2.13.x |2021-01-30 |2.14.0
|2.12.x |2021-01-02 |2.13.0
|2.11.x |2020-11-03 |2.12.0
|2.10.x |2020-10-15 |2.11.0
|2.9.x |2020-10-10 |2.10.0
|2.8.x |2020-10-02 |2.9.0
|2.7.x |2020-09-26 |2.8.0
|2.6.x |2020-09-05 |2.7.0
|2.5.x |2020-07-29 |2.6.0
|2.4.x |2020-07-24 |2.5.0
|2.3.x |2020-07-22 |2.4.0
|2.2.x |2020-07-21 |2.3.0
|2.1.x |2020-07-15 |2.2.0
|2.0.x |2020-05-14 |2.1.0
|1.14.x |2020-05-06 |3.0.0
|1.13.x |2020-04-19 |1.14.0
|1.12.x |2020-03-31 |1.13.0
|1.11.x |2020-03-15 |1.12.0
|1.10.x |2020-02-30 |1.11.0
|1.9.x |2020-02-25 |1.10.0
|1.8.x |2020-01-23 |1.9.0
|1.7.x |2020-01-18 |1.8.0
|1.6.x |2019-12-28 |1.7.0
|1.5.x |2019-12-09 |1.6.0
|1.4.x |2019-10-09 |1.5.0
|1.3.x |2019-09-22 |1.4.0
|1.2.x |2019-09-13 |1.3.0
|1.1.x |2019-09-04 |1.2.0
|1.0.x |2019-08-06 |1.1.0
|====

include::./upgrade-to-v1.asciidoc[Upgrade to v1.x]

include::./upgrade-to-v2.asciidoc[Upgrade to v2.x]

include::./upgrade-to-v3.asciidoc[Upgrade to v3.x]
