name: OpenTelemetry Export Trace

on:
  workflow_run:
    workflows: [Test]
    types: [completed]

jobs:
  otel-export-trace:
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    steps:
      - name: Export Workflow Trace
        uses: v1v/otel-export-trace-action@v2
        with:
          otlpEndpoint: "${{ secrets.APM_SERVER }}"
          otlpHeaders: "Authorization=Bearer ${{ secrets.APM_TOKEN }}"
          otelServiceName: ${{ github.repository }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
